title: The Travelers
description: "A website for all travelers"
github_repo: "travelor_frontend" 
baseurl: "/travelor_frontend"
future: true
remote_theme: pages-themes/cayman@v0.2.0
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/ai.md
  - navigation/authentication/post.md
  - navigation/authentication/developer.md
  - navigation/authentication/weather.md
  
# GitHub Metadata
github:
  token: YOUR_GENERATED_GITHUB_TOKEN